name: nutriscan
description: A food transparency MVP app that fetches packaged food data by barcode.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^6.4.1
  firebase_auth: ^6.5.1
  firebase_core: ^4.9.0
  firebase_storage: ^13.4.1
  flutter:
    sdk: flutter
  http: ^1.6.0
  image_picker: ^1.1.2
  mobile_scanner: ^7.2.0

dev_dependencies:
  firebase_core_platform_interface: ^7.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
