// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBkszcX7KcFMtVVGkZW0RZSvuk01VAkb0',
    appId: '1:588407772197:web:cbce4a1990423503279bcc',
    messagingSenderId: '588407772197',
    projectId: 'nutriscan-38a97',
    authDomain: 'nutriscan-38a97.firebaseapp.com',
    storageBucket: 'nutriscan-38a97.firebasestorage.app',
    measurementId: 'G-16FPYZTD2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmEb7UhBewS12fRiTK2RLq99f7rhB67Lc',
    appId: '1:588407772197:android:f5ef9ad4111e0f64279bcc',
    messagingSenderId: '588407772197',
    projectId: 'nutriscan-38a97',
    storageBucket: 'nutriscan-38a97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD35pQdTxBtWqikH7Ta0VX8jiOF2rPr6I8',
    appId: '1:588407772197:ios:699a4db6d7642fec279bcc',
    messagingSenderId: '588407772197',
    projectId: 'nutriscan-38a97',
    storageBucket: 'nutriscan-38a97.firebasestorage.app',
    iosBundleId: 'com.example.nutriscan',
  );
}
